### ISSUE TITLE
Create a dns cname to a low ttl entry

### ISSUE THREAD

**Issue by kumy** [geokrety/server-migration#4]
In order to mitigate the service interruption the day d, it would be nice to set right now a dns entry with a low TTL. A low value such as 300s would be appreciated.

Expected current to be:
```
geokrety.org. 300 IN CNAME kofola.geokrety.org.
www.geokrety.org. 3600 IN CNAME geokrety.org.

; current instance
kofola.geokrety.org. 3600 IN A 89.73.140.139
```
The day d, just change to:
```
geokrety.org. 3600 IN CNAME tr1.sys.kumy.org.
```

**Comment by filipsPL** [comment]
Done! But let's wait and check...

**Comment by kumy** [comment]
I don't see any difference, do you have an idea on what could be the problem?
(4 hours later)
```
03:15:07 ~$ host geokrety.org
geokrety.org has address 89.73.140.139

03:15:14 ~$ host kofola.geokrety.org
Host kofola.geokrety.org not found: 3(NXDOMAIN)
```

**Comment by filipsPL** [comment]
Ups! I will fix it in the evening.

**Comment by filipsPL** [comment]
Done!

**Comment by kumy** [comment]
Thanks. We now also have an IPv6 connexion :):)
