### ISSUE TITLE
Create a DNS entry for qualif instance

### ISSUE THREAD

**Issue by kumy** [geokrety/server-migration#6]
Necessary for #5.

May you please create a new dns entry to new server dedicated to qualification.
```
qualif.geokrety.org. 3600 IN CNAME tr1.sys.kumy.org.
```

**Comment by filipsPL** [comment]
Done, but don't close the issue untill we are sure it works.

**Comment by kumy** [comment]
Thanks, may you move your card to the right column please :)

See https://github.com/geokrety/server-migration/projects/1

**Comment by kumy** [comment]
Works for me.
